### ISSUE TITLE
can't find a python file 

### ISSUE THREAD

**Issue by J-Wu97** [bhpfelix/MTLNAS#2]
when ran the 'visualization.py' file under the core.utils, the codes line 'from core.models.stagewise_search import vgg_stage_wise_connectivity_matrix_cross_task' occures a error as there is no 'stagewise_search' under the file of core.models.
I hope you can check whether forgetting put the python file in the project. 
Thank you for your reply !

**Comment by bhpfelix** [comment]
Hi, thanks for pointing it out. The `__main__()` in `visualization.py`  was only meant for testing purposes when the code was developed. As the codebase was finalized, some function names and filenames have been changed and the `__main__()` function became deprecated. Though this does not impact any usage of `visualization.py` in the main program. I have removed `__main__()` to avoid any future confusion.
