### ISSUE TITLE
where is configs/defaults.py

### ISSUE THREAD

**Issue by zzz123xyz** [bhpfelix/MTLNAS#3]
Interesting paper and code. However, there is an inconsistency in the read me. where is the configs/defaults.py. there are only two folders: vgg and ablation. Could you help with this 

Thanks

**Comment by bhpfelix** [comment]
Hi, thanks for pointing that out! The correct path should be `core/config/defaults.py`. I have updated README.md accordingly.

**Comment by zzz123xyz** [comment]
Thanks so much 👍
